# Generated by Django 3.0.5 on 2020-04-21 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gsheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscredentials',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
