# Generated by Django 3.0.5 on 2020-04-21 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('guid', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=127, null=True)),
            ],
        ),
    ]
